### PR TITLE
Add basic support Heroku

### PR DESCRIPTION
**Pull request by Macleykun**
This pull is focused on bringing seperate support for the website repo to work with Heroku.

At this point, the user needs to use the following buildpacks manually:
```
heroku/php
https://github.com/weibeld/heroku-buildpack-run
heroku/nodejs
```
The order is very important, otherwise it won't compile completely.

The pull does the following withoud touching the codebase:
postinstall, after node is installed on the machine, the postinstall will be ran everytime.
buildpack-run.sh, will firstly remove the package-lock.json, this is done because two node package managers are used. As Heroku suggest using only one, using this methode we can ensure to use both like it's normally inteded by the developer.
Procfile, well by now you know what it is for, but specifying the public/ ensures on the root of the site, the content of the folder public is shown.

**The .env file must be present and filled with database credentials atleast!**

Feel free to ask about anything related to the pull request.

The next pull will provide full/official support by adding the app.json.
Possible, if websockets are implemented, and changes have to happen, then this pull will be submitted beforehand, as eventually, a hybrid solution between the two repo's should be realised.

### CODE REVIEW

**Review by Senither — APPROVED** [review]
Looks good, thanks for working on adding support for Heroku for the website as well.

I can go ahead and merge the PR now if you're done with it, the only thing that might be nice to have is a setup guide for how to actually set up everything on Heroku(similarly to how there is a setup guide for hosting the website normally), however it might be an idea to write that as a github wiki page instead, or at the very least wait until the website is in a more finished stage.

**Comment by Macleykun** [comment]
You can pull it, this stage is for basic support.
From this base (with your changes that come later) I can work to bring easy deployment and maybe even integration with avaire.
Wiki and all will come when all of the above is certain and tested. Otherwise I would be rewriting :p


________________________________
Van: Alexis Tan <notifications@github.com>
Verzonden: dinsdag, juni 18, 2019 3:11 PM
Aan: avaire/website
CC: Macley; Author
Onderwerp: Re: [avaire/website] Basic support Heroku (#2)


@Senither approved this pull request.

Looks good, thanks for working on adding support for Heroku for the website as well.

I can go ahead and merge the PR now if you're done with it, the only thing that might be nice to have is a setup guide for how to actually set up everything on Heroku(similarly to how there is a setup guide for hosting the website normally), however it might be an idea to write that as a github wiki page instead, or at the very least wait until the website is in a more finished stage.

―

**Comment by Senither** [comment]
Alrighty, all good, the plan is to eventually to move all the documentation from the website into GitHub wiki pages for both Ava, the website, and related projects, which was why I suggested it before.

**Comment by Macleykun** [comment]
👍

**Pull request merged**
